# Generated by Django 4.2.3 on 2023-08-09 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_studentprofile_bio_studentprofile_profile_pics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='quantity',
        ),
    ]
